export const GENRES = [
  'Acceptable Country',
  'Acceptable Emo',
  'Acceptable Pop',
  'Acceptable Pop-Punk',
  'Alt-Country',
  'Alt-Rap',
  'Bloghaus',
  'Blog Rap',
  'Blog Rock',
  'Cold Wave',
  'Cool Jazz',
  'Digital Punk',
  'Doom Metal',
  'Freak Folk',
  'Garage Rock',
  'Hypnagogic Pop',
  'Noise Pop',
  'Power Electronics',
  'Serialism',
  'Witch House',
  'Ye Olde Timey Rock And Roll Music of Indeterminate Hipster Variety'
];
